name = "Davlux"
description = "a minimal hugo theme" 

license = "GNU GPLv3"
licenselink = "https://github.com/mansoorbarri/davlux/blob/main/LICENCE"

homepage = "https://github.com/mansoorbarri/davlux"
demosite = "https://davlux.mansoorbarri.com/"

tags = ["minimal", "dark", "personal"]

authors = [
  {name = "Mansoor Barri", homepage = "https://mansoorbarri.com"},
]

min_version = "0.111.3"
